### ISSUE TITLE
 Failed to set MTU for adapter

### ISSUE THREAD

**Issue by lemos1235** [tun2proxy/wintun-bindings#10]
os: windows 11
error message: 
```
[2024-12-12T03:05:58Z ERROR wintun_bindings::util] Failed to set MTU for adapter: Run command: "netsh interface ipv4 set subinterface "wintun" mtu=65535 store=persistent" failed with "The parameter is incorrect.
    
    
    "
Error: WintunError(Io(Custom { kind: Other, error: "Run command: \"netsh interface ipv4 set subinterface \"wintun\" mtu=65535 store=persistent\" failed with \"The parameter is incorrect.\r\n\r\n\r\n\"" }))
```

if run it directly in command line:
C:\Users\admin>netsh interface ipv4 set subinterface "wintun" mtu=65535 store=persistent
The filename, directory name, or volume label syntax is incorrect.

**Comment by ssrlive** [comment]
On your PC, how about running this command?
```bash
netsh interface ipv4 set subinterface "Wi-Fi" mtu=1490
```
Here "Wi-Fi" is your outting Network Adapter name.

**Comment by lemos1235** [comment]
that's ok.  `netsh interface ipv4 set subinterface "Wi-Fi" mtu=65535` got that error

**Comment by ssrlive** [comment]
Now I give a new commit, can you get it a test? https://github.com/tun2proxy/wintun-bindings/commit/61d39b00af39f0ca7bc03550628aad70a5e6e623

**Comment by lemos1235** [comment]
it's ok now

**Comment by ssrlive** [comment]
New version published.
