### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vnt-dev** [tun2proxy/wintun-bindings#12]
\wintun-bindings-0.7.25\src\log.rs:29:23
   |
29 | static LOG_CONTAINER: std::sync::LazyLock<std::sync::Mutex<std::collections::VecDeque<LogItem>>> =
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'

**Comment by ssrlive** [comment]
Oops, please use rust version 1.80 or above.

**Comment by vnt-dev** [comment]
Is it too hasty to abandon versions before 1.8 like this

**Comment by vnt-dev** [comment]
Alternatively, version="0.8.x" should be used

**Comment by ssrlive** [comment]
I think I can add a feature for it.

**Comment by ssrlive** [comment]
done.
