### ISSUE TITLE
Wintun adapter does not specify as thread-safe

### ISSUE THREAD

**Issue by vnt-dev** [tun2proxy/wintun-bindings#4]
```
pub struct Adapter {
    adapter: UnsafeHandle<wintun_raw::WINTUN_ADAPTER_HANDLE>,
    pub(crate) wintun: Wintun,
    guid: u128,
    index: u32,
    luid: NET_LUID_LH,
}

fn create(..)->Arc<Adapter>
/// undefined behavior
fn start_session(self: &Arc<Self>)->Arc<Session>
```

**Comment by ssrlive** [comment]
How crazy a user must be to think of frequently creating and destroying sessions. 
If I remember correctly, this adapter is designed to serve `one` session. 
If you want to create another session, something may go wrong. 
You can Check it in the source code or try to fix it.
