### ISSUE TITLE
MTU 

### ISSUE THREAD

**Issue by vnt-dev** [tun2proxy/wintun-bindings#8]
The setting of MTU has not taken effect. It may have been caused by the submission of 'refactor set_adapter_mtu function'.

**Comment by ssrlive** [comment]
Just finished testing, neither the command line nor the Windows API can actually change the MTU of the Wintun adapter. The intention of the committed modification is to circumvent the problem that using the command line may fail on some Windows 7 systems.

![image](https://github.com/user-attachments/assets/46dcd952-f239-4f05-a953-ec1556fd4212)

**Comment by vnt-dev** [comment]
`netsh interface ipv4 set subinterface "tun0" mtu=1500`
![image](https://github.com/user-attachments/assets/f719f642-62da-4de7-b24f-8a789fc9d20d)
`netsh interface ipv4 set subinterface "tun0" mtu=1420`
![image](https://github.com/user-attachments/assets/fb7ff1f0-89b6-4103-914b-e7b1cf750098)

**Comment by vnt-dev** [comment]
The MTU value has been modified, and the network adapter will perform IP fragmentation according to the corresponding MTU. That's sufficient.
